CREATE TABLE PARTNER (
  PARTNER_CODE INTEGER NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  PHONE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  RATING INTEGER NOT NULL,
  PRIMARY KEY (PARTNER_CODE)
);
